### ISSUE TITLE
String with more than one single quotes become double escaped

### ISSUE THREAD

**Issue by guyaumetremblay** [nicklayb/php_assoc_map#14]
Hi @nicklayb ,

I got a special issue with the latest version (still in Accent, so don't know on which project is the error).

Giving a localization file like this one: 

```
<?php
return [
  'title'=>'L\'utilisation de l\'application',
];
```
So, a string with multiple single quote, already escaped. 

If I try an `accent sync` or `accent format`, the file become invalid and look like this: 

```
<?php
return [
  'title'=>'L\'utilisation de l\\'application',
];
```

The second single quote in the string is escaped 2 times. 
If I put the string in double quotes and remove the escaping, `accent format` will bring it back to a single quoted string, escaped. So the issue happen the second time. 

I hope you got enough informations!

Thanks in advance.

**Comment by guyaumetremblay** [comment]
@nicklayb 
Sorry, I can't send a PR for this right now but I think the fix should be here: https://github.com/nicklayb/php_assoc_map/blob/c9352d78b9ea1fa974829abb8fc29bbbc29d0ac5/lib/utils.ex#L25

Where, the replace should use a regex to replace all occurence instead of the first one.

**Comment by nicklayb** [comment]
`String.replace/2` correctly replaces all the occurences, the below assertions passes fine

```
assert Utils.stringify("L'utilisation de l'application") == "'L\\'utilisation de l\\'application'"
```
I'll have a look where this can come from

**Comment by guyaumetremblay** [comment]
Yes, the problem appear when the strings is already escaped like:
"L\'utilisation de l\' application"
Which give "L\'utilisation de l\\' application"

I think with a negative lookbehind regex it should work

**Comment by nicklayb** [comment]
The problem most likely lies on the lexer's regex actually and how strings and charlist are parsed ([here](https://github.com/nicklayb/php_assoc_map/blob/c9352d78b9ea1fa974829abb8fc29bbbc29d0ac5/src/php_lang.xrl#L17) to be precised))

**Comment by nicklayb** [comment]
![image](https://github.com/nicklayb/php_assoc_map/assets/15114240/04271e01-d65d-438a-98fa-d50e3af82416)

That's gonna be a fun one

**Comment by nicklayb** [comment]
Nevermind, it parses fine, it's [in the parser](https://github.com/nicklayb/php_assoc_map/blob/c9352d78b9ea1fa974829abb8fc29bbbc29d0ac5/src/php_parse.yrl#L26).

Probably what you said about the regex but this instance rather the utils one.

EDIT: Got it, I was missing the  `global` flag in the regex!

**Comment by nicklayb** [comment]
Fixed by #15

**Comment by guyaumetremblay** [comment]
Thanks @nicklayb and sorry for the delay! I was waiting for a new version in accent to try it (for some reason, I had issue with my local setup). 
I can now confirm that the fix is working! 🎉

**Comment by nicklayb** [comment]
Really happy to read that, don't hesitate if you find anything else odd!

**Comment by guyaumetremblay** [comment]
@nicklayb Thanks. The only thing left is the code style of the output (the dump in the php file at the end of the sync in accent) which is making my phpcs very sad! 
But right now, I don't know if it's cause by this lib and if it's customizable 

Ex:
```
<?php

return [
  'title' => 'Something',
];
```
Became

```
<?php
return [
  'title'=>'Something',
];
```
- Header blocks must be separated by a single blank linephpcs
- Expected at least 1 space before "=>"; 0 found
