### ISSUE TITLE
Can't parse Laravel localization file containing string with single quote

### ISSUE THREAD

**Issue by guyaumetremblay** [nicklayb/php_assoc_map#9]
From https://github.com/mirego/accent/issues/380

Hi,

This issue was observed into [Accent](https://github.com/mirego/accent/).

Using a Laravel PHP localization file, if a string (double quoted) contains a single quote, the file cannot be parsed. For example:
```
<?php

return [
    'foo' => [
        'bar' => [
            'cta' => "Confirmer à l'équipe"
        ]
    ]
];
```

With this file, the accent cli return this message:

```
 ›   Error: file cannot be parsed
```

Single quoted string, escaping the single quote like this, doesn't work either:

```
<?php

return [
    'foo' => [
        'bar' => [
            'cta' => 'Confirmer à l\'équipe'
        ]
    ]
];
```

We are using both across our laravel projects.

Thanks for your help!

**Comment by guyaumetremblay** [comment]
Hi @nicklayb, 
Did you get the time to look at this?

**Comment by nicklayb** [comment]
> Hi @nicklayb, Did you get the time to look at this?

I tried to look the other day, what I'm pretty sure I can confirm is that this works out of php_assoc_map. I tried to update the version on accent but had a couple of hiccups with my dev environment (haven't investigate much but I wasn't able to run accent at all it couldn't find the database). But I'm pretty sure that bumping to `1.0.1` should address the issue. I'll try again later this week probably

**Comment by guyaumetremblay** [comment]
> > Hi @nicklayb, Did you get the time to look at this?
> 
> I tried to look the other day, what I'm pretty sure I can confirm is that this works out of php_assoc_map. I tried to update the version on accent but had a couple of hiccups with my dev environment (haven't investigate much but I wasn't able to run accent at all it couldn't find the database). But I'm pretty sure that bumping to `1.0.1` should address the issue. I'll try again later this week probably

I hope this is just that! 
I just build from source a docker image of accent with the 1.0.1 of this library... but now, a simple file like that doesn't parse anymore: 
```
<?php

return [
    'title' => 'Foo'
];
```
Using this config: 
```
{
    "apiUrl": "http://localhost:4000/",
    "apiKey": "some-key",
    "files": [
      {
        "language": "en",
        "format": "laravel_php",
        "source": "resources/lang/en/*.php",
        "target": "resources/lang/%slug%/%document_path%.php"
      }
    ]
  }
```

Output: 
```
accent sync --dry-run
Fetch config in accent.json... API Client ✓

Syncing sources → fr  ✓

 ›   Error: file cannot be parsed
```

I hope this can help you!

**Comment by nicklayb** [comment]
There was another issue with special characters (ironically, it couldn't parse accents :sweat_smile:). This is addressed as of 2.0.0

**Comment by nicklayb** [comment]
I opened [this PR](https://github.com/mirego/accent/pull/389) on Accent to fix the issue

**Comment by guyaumetremblay** [comment]
@nicklayb Wonderful! Thanks a lot! 
I tried your branch and it works well! 
Just got one other issue: it doesn't like a trailing coma but I will open another issue.

**Comment by nicklayb** [comment]
Oh yeah that's possible, shouldn't be a big deal, I'll update my branch as well before it gets merged
